AWSTemplateFormatVersion: 2010-09-09
Description: Test

# aws cloudformation deploy --stack-name test --template-file security-groups.yaml --parameter-overrides VpcId=vpc-029e833f59096dd29 --profile frankfurt

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}-SG"
      GroupDescription: "Test"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - Description: "Inline1-WithoutCidr"
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - Description: "Inline2-WithCidr"
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.181.11.26/32
        - Description: "Inline3-WithCidr"
          IpProtocol: tcp
          FromPort: 22 
          ToPort: 22
          CidrIp: 10.106.32.0/22
  InboundRule1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "AttachedWithCidr"
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      CidrIp: 10.181.11.24/32
      GroupId:
        Fn::GetAtt:
          - SecurityGroup
          - GroupId          
  InboundRule2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "AttachedWithoutCidr"
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535      
      GroupId:
        Fn::GetAtt:
          - SecurityGroup
          - GroupId              